### ISSUE TITLE
Leak sanitizer complains about memory leaks for tests/test-i-https.c

### ISSUE THREAD

**Issue by rootkea** [rockdaboot/wget2#162]
Reproducible with:

    ./configure --enable-fsanitize-msan
    make clean
    make check

Relevant output from test-i-https.log

    ==9579==ERROR: LeakSanitizer: detected memory leaks

    Direct leak of 16 byte(s) in 1 object(s) allocated from:
        #0 0x7f339f28b433 in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/liblsan.so.0+0xb433)
        #1 0x7f339e4de28a in gnutls_x509_crl_iter_crt_serial (/usr/lib/x86_64-linux-gnu/libgnutls-deb0.so.28+0x6d28a)

    SUMMARY: LeakSanitizer: 16 byte(s) leaked in 1 allocation(s). 

With valgrind:

    ./configure --enable-valgrind-tests
    make clean
    make check TESTS=test-i-https

Relevant output from test-i-https.log:

    ==16146== HEAP SUMMARY:
    ==16146==     in use at exit: 16 bytes in 1 blocks
    ==16146==   total heap usage: 40,204 allocs, 40,203 frees, 10,377,439 bytes allocated
    ==16146== 
    ==16146== 16 bytes in 1 blocks are definitely lost in loss record 1 of 1
    ==16146==    at 0x4C2AD10: calloc (vg_replace_malloc.c:623)
    ==16146==    by 0x599228A: gnutls_x509_crl_iter_crt_serial (in /usr/lib/x86_64-linux-gnu/libgnutls-deb0.so.28.41.0)
    ==16146==    by 0x59B5908: ??? (in /usr/lib/x86_64-linux-gnu/libgnutls-deb0.so.28.41.0)
    ==16146==    by 0x59BC41E: gnutls_x509_trust_list_verify_crt2 (in /usr/lib/x86_64-linux-gnu/libgnutls-deb0.so.28.41.0)
    ==16146==    by 0x59712BE: ??? (in /usr/lib/x86_64-linux-gnu/libgnutls-deb0.so.28.41.0)
    ==16146==    by 0x5967A87: gnutls_certificate_verify_peers3 (in /usr/lib/x86_64-linux-gnu/libgnutls-deb0.so.28.41.0)
    ==16146==    by 0x4E61D72: _verify_certificate_callback (in /home/rootkea/Documents/gsoc/wget2/libwget/.libs/libwget.so.0.0.0)
    ==16146==    by 0x59539CB: ??? (in /usr/lib/x86_64-linux-gnu/libgnutls-deb0.so.28.41.0)
    ==16146==    by 0x59580FB: gnutls_handshake (in /usr/lib/x86_64-linux-gnu/libgnutls-deb0.so.28.41.0)
    ==16146==    by 0x4E62CCA: _do_handshake (in /home/rootkea/Documents/gsoc/wget2/libwget/.libs/libwget.so.0.0.0)
    ==16146==    by 0x4E6345B: wget_ssl_open (in /home/rootkea/Documents/gsoc/wget2/libwget/.libs/libwget.so.0.0.0)
    ==16146==    by 0x4E5CC60: wget_tcp_connect (in /home/rootkea/Documents/gsoc/wget2/libwget/.libs/libwget.so.0.0.0)
    ==16146== 
    ==16146== LEAK SUMMARY:
    ==16146==    definitely lost: 16 bytes in 1 blocks

**Comment by rockdaboot** [comment]
- You should add -g to your CFLAGS - with that you could see line numbers !
- Looks like a gnutls issue - I can't reproduce it with GnuTLS 3.5.8 here, so maybe Nikos already fixed it.

**Comment by rockdaboot** [comment]
That's why it makes sense to have a recent system for developing. You won't stumble upon bugs that already have been fixed :-)

**Comment by rootkea** [comment]
> You should add -g to your CFLAGS - with that you could see line numbers !

Thanks. And I thought it was because my `gcc` was old. Didn't read the manual the first time you mentioned `-g`. My bad!

BTW I added `-g` to CFLAGS but still can't see line numbers. I guess it's because memory leak is reported in lib and not in source file.

> That's why it makes sense to have a recent system for developing.

Ha ha! Indeed. I'll either set up QEMU+Ubuntu/Arch or dual boot with Ubuntu/Arch.

**Comment by rockdaboot** [comment]
> I guess it's because memory leak is reported in lib and not in source file.
Yepp. Some libraries have -dbg versions, e.g.
```
$ apt-cache search libgnutls|grep -- -dbg
libgnutls28-dbg - GNU TLS library - debugger symbols
```

**Comment by rootkea** [comment]
I installed debugger symbols for libgnutls but still seeing same log *without* line numbers. But since this concerns libgnutls may be I should not discuss that issue here on wget2.

**Comment by rootkea** [comment]
Ok. So to get rid of the memory leak in GnuTLS and thus of that 1 failed test after `make check` I built and installed gnutls-3.5.9 but now `./configure` says:  

    ...  
    checking for GNUTLS... no  
    ...

Though the final output of `./configure` has SSL support as:

    Libs:               -lidn2 -llzma  -L/usr/lib/x86_64-linux-gnu -lz  -lbz2 -lgnutls 
    SSL/TLS support:    yes  

May be the latest version of GnuTLS expects some new/modified flags. Not sure. I'm still looking into it.

**Comment by rockdaboot** [comment]
You have to set LDFLAGS, e.g. to `-L/usr/local/lib`. I don't have it in mind exactly, sorry. Also search the internet if that doesn't work out. I am back in the office later... oh yes, there is also GNUTLS_LIBS and/or PKG_CONFIG* if you work with pkg-config (likely).

**Comment by rootkea** [comment]
Yes. I think I got the culprit.

    $ cat config.log  
    ...
    configure:46684: checking for GNUTLS
    configure:46691: $PKG_CONFIG --exists --print-errors "gnutls"
    Package libidn2 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libidn2.pc'
    to the PKG_CONFIG_PATH environment variable
    ... 

I'll get back once I fix this.

**Comment by rockdaboot** [comment]
After installing a library you might need to call `ldconfig`.

**Comment by rootkea** [comment]
`ldconfig` didn't help and also I found that there was a same bug in GnuTLS which got closed[0] So building GnuTLS-3.5.9 was smooth. It identified libidn2.

Problem is when I try to build wget2.

[0] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=855888

**Comment by rockdaboot** [comment]
When you are compiling GnuTLS, you should end up with 3.5.11 (current version).

When compiling Wget2 with your local GnuTLS (e.g. installed to /usr/local/...), I can use
```
$ GNUTLS_LIBS="-L/usr/local/lib" ./configure && make
$ ldd src/.libs/wget2 |grep gnutls
        libgnutls.so.30 => /usr/local/lib/libgnutls.so.30 (0x00007ff305805000)
```

**Comment by rootkea** [comment]
Oh! I completely overlooked 3.5.1x versions and went straight to 3.5.9! Also it looks like the mirror at https://www.gnupg.org/ftp/gcrypt/gnutls/v3.5/ doesn't have 3.5.11

Downloading the latest version now then will use GNUTLS_LIBS variable. Thanks!

**Comment by rootkea** [comment]
So I installed GnuTLS-3.5.11 but still the wget2 build fails.  

    $ GNUTLS_LIBS="-L/usr/local/lib" ./configure && make  
    ...
    ./.libs/libwget.so: undefined reference to `gnutls_session_get_flags'
    collect2: error: ld returned 1 exit status
    Makefile:1513: recipe for target 'test_linking' failed
    make[2]: *** [test_linking] Error 1
    make[2]: Leaving directory '/home/rootkea/Documents/gsoc/wget2/libwget'
    Makefile:1513: recipe for target 'all-recursive' failed
    make[1]: *** [all-recursive] Error 1
    make[1]: Leaving directory '/home/rootkea/Documents/gsoc/wget2'
    Makefile:1421: recipe for target 'all' failed
    make: *** [all] Error 2

Also I think `GNUTLS_LIBS="-L/usr/local/lib"` is maybe unnecessary as `./configure` output shows Libs as:  

    Libs:               -lidn2 -llzma  -L/usr/lib/x86_64-linux-gnu -lz  -lbz2 -L/usr/local/lib -lgnutls

**Comment by rockdaboot** [comment]
Somehow you link with an older version of GnuTLS. Do a `make clean && make`. And check the version that will libwget links to (`ldd libwget/.libs/libwget.so`).

**Comment by rootkea** [comment]
You are right.

    $ ldd libwget/.libs/libwget.so
    libgnutls-deb0.so.28 => /usr/lib/x86_64-linux-gnu/libgnutls-deb0.so.28 (0x00007ff7bbb90000)

Now I can't remove libgnutls-deb0-28 as when I tried doing that it showed tons of other packages which will get removed along with it. So how do I instruct make to link with the libgnutls from /usr/local/lib and not from /usr/lib/x86_64-linux-gnu?

May be I should install GnuTLS-3.5.11 in /usr/lib/x86_64-linux-gnu? I hope doing so doesn't screw with other packages.

**Comment by rockdaboot** [comment]
> May be I should install GnuTLS-3.5.11 in /usr/lib/x86_64-linux-gnu overwriting the older version? I hope doing so doesn't screw with other packages.

:-) No, you shouldn't. 

* Check if /usr/local/lib really contains your new version of libgnutls.
* Try again: `GNUTLS_LIBS="-L/usr/local/lib" ./configure && make clean && make` (then check with above ldd command)
* cd into libwget, make clean, make V=1 to see the linker command line that creates libwget.so. Does it look right or wrong ?
* Try again with: `LDFLAGS="-L/usr/local/lib" GNUTLS_LIBS="-L/usr/local/lib" ./configure && make clean && make`

If it still doesn't work... *scratch*

**Comment by rootkea** [comment]
`LDFLAGS="-L/usr/local/lib"` did the trick! I think the problem was (with or without GNUTLS_LIBS) that `-L/usr/local/lib` was coming *after* `-L/usr/lib/x86_64-linux-gnu` on command line. This can be seen above in Libs part of `./configure` output. So linker was picking `libgnutls` from the first location it found. 

Thank you very much!

I am going to add `LDFLAGS="-L/usr/local/lib"` in my .bashrc to avoid typing it every time!

**Comment by rockdaboot** [comment]
Good to know. I think it's different here because of pkg-config stuff. However...
